//
//  MainRootPresenter.swift
//  news-app
//
//  Created by minhnv1 on 01/03/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

protocol MainRootPresentationLogic {
    func presentResponse(_ response: MainRootModel.Response)
}

final class MainRootPresenter {
    private weak var viewController: MainRootDisplayLogic?

    init(viewController: MainRootDisplayLogic?) {
        self.viewController = viewController
    }
}


// MARK: - MainRootPresentationLogic
extension MainRootPresenter: MainRootPresentationLogic {

    func presentResponse(_ response: MainRootModel.Response) {

        switch response {

        case .doSomething(let theNewItem, let isItem):
            presentDoSomething(theNewItem, isItem)
        }
    }
}


// MARK: - Private Zone
private extension MainRootPresenter {

    func presentDoSomething(_ newItem: Int, _ isItem: Bool) {

        //prepare data for display and send it further

        viewController?.displayViewModel(.doSomething(viewModelData: NSObject()))
    }
}
