//
//  SignInPresenter.swift
//  news-app
//
//  Created by minhnv1 on 01/03/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import Foundation

protocol SignInPresentationLogic {
  func presentResponse(_ response: SignInModel.Response)
}

final class SignInPresenter {
  private weak var viewController: SignInDisplayLogic?
  
  init(viewController: SignInDisplayLogic?) {
    self.viewController = viewController
  }
}


// MARK: - SignInPresentationLogic
extension SignInPresenter: SignInPresentationLogic {
  
  func presentResponse(_ response: SignInModel.Response) {
    
    switch response {
      
    case .doSomething(let theNewItem, let isItem):
      presentDoSomething(theNewItem, isItem)
    }
  }
}


// MARK: - Private Zone
private extension SignInPresenter {
  
  func presentDoSomething(_ newItem: Int, _ isItem: Bool) {
    
    //prepare data for display and send it further
    
    viewController?.displayViewModel(.doSomething(viewModelData: NSObject()))
  }
}
