//
//  SignInView.swift
//  news-app
//
//  Created by minhnv1 on 01/03/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol SignInViewDelegate where Self: UIViewController {

    func sendDataBackToParent(_ data: Data)
}

final class SignInView: CustomViewWithXib {

    weak var delegate: SignInViewDelegate?

    @IBOutlet weak var userNameTextField: NewsCommonTextField!
    @IBOutlet weak var passwordTextField: NewsCommonTextField!
    @IBOutlet weak var signInUpButton: UIButton!
    @IBOutlet weak var orSignWithLabel: UILabel!
    @IBOutlet weak var termAndConditionLabel: UILabel!
}

extension SignInView: CustomizeViewAfterLoadNib {
    func customizeView() {
        userNameTextField.label.text = localized(key: "authen_email")
    }
}
