//
//  SignInView.swift
//  news-app
//
//  Created by minhnv1 on 01/03/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit
import Combine

protocol SignInViewDelegate where Self: UIViewController {

    func textFieldDidBeginEditing(_ textField: UITextField)
}

final class SignInView: CustomViewWithXib {

    weak var delegate: SignInViewDelegate?

    @IBOutlet weak var userNameTextField: NewsCommonTextField!
    @IBOutlet weak var passwordTextField: NewsCommonTextField!
    @IBOutlet weak var signInUpButton: UIButton!
    @IBOutlet weak var orSignWithLabel: UILabel!
    @IBOutlet weak var termAndConditionLabel: UILabel!

    static let userNameTextFieldTag = 999
    static let passwordTextFieldTag = 998

    required init?(coder: NSCoder) {
        super.init(coder: coder)
    }

    override init(frame: CGRect) {
        super.init(frame: frame)
    }
}

extension SignInView: CustomizeUIAfterLoadNib {
    func customizeUI() {
        userNameTextField.textField.borderStyle = .none
        userNameTextField.textField.delegate = self
        userNameTextField.textField.tag = SignInView.userNameTextFieldTag
        userNameTextField.rightButton.setImage(nil, for: .normal)
        userNameTextField.subLabel.isHidden = true

        passwordTextField.textField.borderStyle = .none
        passwordTextField.textField.tag = SignInView.passwordTextFieldTag
        passwordTextField.rightButton.tintColor = .black
        passwordTextField.subLabel.isHidden = true
        passwordTextField.textField.isSecureTextEntry = true
    }
}

extension SignInView: UITextFieldDelegate {
    func textFieldDidBeginEditing(_ textField: UITextField) {
        delegate?.textFieldDidBeginEditing(textField)
    }
}
