//
//  SignInRouter.swift
//  news-app
//
//  Created by minhnv1 on 01/03/2024.
//  Copyright (c) 2024 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the VIP Swift Xcode Templates(https://github.com/Andrei-Popilian/VIP_Design_Xcode_Template)
//  so you can apply clean architecture to your iOS and MacOS projects,
//  see more http://clean-swift.com
//

import UIKit

protocol SignInRouting {
  
  func routeTo(_ route: SignInModel.Route)
}

final class SignInRouter {
  
  private weak var viewController: UIViewController?
  
  init(viewController: UIViewController?) {
    self.viewController = viewController
  }
}


// MARK: - SignInRouting
extension SignInRouter: SignInRouting {
  
  func routeTo(_ route: SignInModel.Route) {
    DispatchQueue.main.async {
      switch route {
        
      case .dismissSignInScene:
        self.dismissSignInScene()
        
      case .xScene(let data):
        self.showXSceneBy(data)
      }
    }
  }
}


// MARK: - Private Zone
private extension SignInRouter {
  
  func dismissSignInScene() {
    viewController?.dismiss(animated: true)
  }
  
  func showXSceneBy(_ data: Int) {
    print("will show the next screen")
  }
}
